/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author jyarango
 */
public class FExpediente extends javax.swing.JFrame {

    /**
     * Creates new form Expediente
     */
    public FExpediente() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtCliente = new javax.swing.JTextField();
        jtxtMonto = new javax.swing.JTextField();
        jtxtCodigoExpediente = new javax.swing.JTextField();
        jtxtPlazo = new javax.swing.JTextField();
        jbtnConsultar = new javax.swing.JButton();
        jbtnCalcularCuota = new javax.swing.JButton();
        jLabel67 = new javax.swing.JLabel();
        jtxtFechaRegistro = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jbtnActualizar = new javax.swing.JButton();
        jcbxMoneda = new javax.swing.JComboBox<>();
        jcbxCiclica = new javax.swing.JComboBox<>();
        jcbxTipoSeg = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jtxtTea = new javax.swing.JTextField();
        jtxtCuota = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtAprobacion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtxtEstado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtDescripcion = new javax.swing.JTextArea();
        jbtnGrabar = new javax.swing.JButton();
        jbtnAprobar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblExpediente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EXPEDIENTE");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CODIGO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FECHA REGISTRO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CLIENTE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MONEDA");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("MONTO");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));
        jPanel2.add(jtxtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 190, 30));
        jPanel2.add(jtxtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 190, 30));
        jPanel2.add(jtxtCodigoExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 190, 30));
        jPanel2.add(jtxtPlazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 190, 30));

        jbtnConsultar.setBackground(new java.awt.Color(0, 51, 153));
        jbtnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jbtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 50, 30));

        jbtnCalcularCuota.setBackground(new java.awt.Color(0, 51, 153));
        jbtnCalcularCuota.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCalcularCuota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calc.png"))); // NOI18N
        jbtnCalcularCuota.setText("CALCULAR CUOTA");
        jbtnCalcularCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcularCuotaActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCalcularCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 40));

        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("PLAZO");
        jPanel2.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));
        jPanel2.add(jtxtFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 190, 30));

        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("CICLICA");
        jPanel2.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("DESCRIPCIÓN");
        jPanel2.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("TIPO DE SEGURO");
        jPanel2.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        jbtnActualizar.setBackground(new java.awt.Color(0, 51, 153));
        jbtnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        jbtnActualizar.setText("ACTUALIZAR");
        jPanel2.add(jbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 170, 50));

        jcbxMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jcbxMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 190, 40));

        jcbxCiclica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jcbxCiclica, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 190, 40));

        jcbxTipoSeg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jcbxTipoSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 190, 40));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jtxtTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 150, 30));
        jPanel3.add(jtxtCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 150, 30));

        jLabel68.setText("ESTADO");
        jPanel3.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel18.setText("TEA");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel6.setText("FECHA APROBACIÓN");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));
        jPanel3.add(jtxtAprobacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 190, 30));

        jLabel19.setText("CUOTA");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));
        jPanel3.add(jtxtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 190, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 850, 140));

        jtxtDescripcion.setColumns(20);
        jtxtDescripcion.setRows(5);
        jScrollPane2.setViewportView(jtxtDescripcion);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jbtnGrabar.setBackground(new java.awt.Color(0, 51, 153));
        jbtnGrabar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        jbtnGrabar.setText("GRABAR");
        jbtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGrabarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 170, 50));

        jbtnAprobar.setBackground(new java.awt.Color(153, 0, 153));
        jbtnAprobar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAprobar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aprobar.png"))); // NOI18N
        jbtnAprobar.setText("APROBAR");
        jbtnAprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAprobarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnAprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 170, 50));

        jbtnEliminar.setBackground(new java.awt.Color(0, 51, 153));
        jbtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        jbtnEliminar.setText("ELIMINAR");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 170, 50));

        jTabbedPane1.addTab("EXPEDIENTE", jPanel2);

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RELACIÓN DE EXPEDIENTES");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jtblExpediente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblExpediente);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 830, -1));

        jTabbedPane1.addTab("RELACION", jPanel5);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnAprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAprobarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAprobarActionPerformed

    private void jbtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGrabarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnGrabarActionPerformed

    private void jbtnCalcularCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcularCuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCalcularCuotaActionPerformed

    private void jbtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FExpediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JButton jbtnActualizar;
    public javax.swing.JButton jbtnAprobar;
    public javax.swing.JButton jbtnCalcularCuota;
    public javax.swing.JButton jbtnConsultar;
    public javax.swing.JButton jbtnEliminar;
    public javax.swing.JButton jbtnGrabar;
    public javax.swing.JComboBox<String> jcbxCiclica;
    public javax.swing.JComboBox<String> jcbxMoneda;
    public javax.swing.JComboBox<String> jcbxTipoSeg;
    public javax.swing.JTable jtblExpediente;
    public javax.swing.JTextField jtxtAprobacion;
    public javax.swing.JTextField jtxtCliente;
    public javax.swing.JTextField jtxtCodigoExpediente;
    public javax.swing.JTextField jtxtCuota;
    public javax.swing.JTextArea jtxtDescripcion;
    public javax.swing.JTextField jtxtEstado;
    public javax.swing.JTextField jtxtFechaRegistro;
    public javax.swing.JTextField jtxtMonto;
    public javax.swing.JTextField jtxtPlazo;
    public javax.swing.JTextField jtxtTea;
    // End of variables declaration//GEN-END:variables
}
