/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.*;
import javax.swing.*;
/**
 *
 * @author jyarango
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(1200, 800);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jbtnExpediente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jbtnCliente = new javax.swing.JButton();
        jbtnCronograma = new javax.swing.JButton();
        jbtnMantenimiento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Group.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        jbtnExpediente.setForeground(new java.awt.Color(255, 255, 255));
        jbtnExpediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edexpediente.png"))); // NOI18N
        jbtnExpediente.setText("EXPEDIENTE");
        jbtnExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExpedienteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 220, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoprincipal.jpg"))); // NOI18N
        jLabel4.setText(" ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1200, 660));

        jbtnCliente.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user1.png"))); // NOI18N
        jbtnCliente.setText("CLIENTE");
        jbtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 220, 50));

        jbtnCronograma.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCronograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cronograma.png"))); // NOI18N
        jbtnCronograma.setText("CRONOGRAMA");
        jbtnCronograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCronogramaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCronograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 220, 50));

        jbtnMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        jbtnMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento.png"))); // NOI18N
        jbtnMantenimiento.setText("GRADO");
        jbtnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMantenimientoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 220, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barrap.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(1200, 60));
        jLabel2.setMinimumSize(new java.awt.Dimension(1200, 60));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void formularios(JFrame form){
          form.setVisible(true);
       form.setBounds(280,400, 900, 640);
        form.setResizable(false);
        form.setLocationRelativeTo(null);
    }
    private void jbtnExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExpedienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnExpedienteActionPerformed

    private void jbtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnClienteActionPerformed

    private void jbtnCronogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCronogramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCronogramaActionPerformed

    private void jbtnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JButton jbtnCliente;
    public javax.swing.JButton jbtnCronograma;
    public javax.swing.JButton jbtnExpediente;
    public javax.swing.JButton jbtnMantenimiento;
    // End of variables declaration//GEN-END:variables
}
